Adds audience field to sign token messages.
DIMO-Network/dex pull request #214
Opened 2024-03-28 13:43 UTC by KevinJoiner

Our JWT tokens are missing the audience field, which is required by many JWT validators, such as this one, which will be needed for our new GQL API: https://github.com/auth0/go-jwt-middleware.

More info on Audience Claim https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3

2024-03-28 13:44 UTC, KevinJoiner commented on Makefile
> +PROTOC_GEN_GO_VERSION      = 1.30.0
The previous generation of our protobuf files used 1.30.0 but the make file was not updated too match

2024-03-28 15:34 UTC, 0xdev22 requested changes
LGTM, but two issues

1. The PR seems to deviate from the original purpose which is to add audience to privilege tokens. I can see we are updating go version here as well. Next time, I would prefer we handle this in a seperate PR
2. Can you fix the lint issues

2024-03-28 17:30 UTC, 0xdev22 commented
LGTM

2024-04-02 13:59 UTC, 0xdev22 approved these changes

2024-04-02 14:00 UTC, merged